### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by Finomnis** [CW-Jesse/valheim-betternetworking#12]
Would it be possible to release a Linux version of this mod for dedicated servers?

I use https://github.com/mbround18/valheim-docker to run my server, and I would love to use this mod.
Willed to donate a couple of coffees for it :)

**Comment by CW-Jesse** [comment]
Hi! Are you running into an error?

**Comment by Finomnis** [comment]
Never mind, I just didn't realize that the `.dll`s are working on linux

**Comment by CW-Jesse** [comment]
Have fun!
