### ISSUE TITLE
may no longer work with new valheim update

### ISSUE THREAD

**Issue by jpw1991** [CW-Jesse/valheim-betternetworking#15]
After updating to the new valheim version I had issues of connecting just taking forever. It may be this mod but I don't know. removing it fixed it

**Comment by Senjiroh** [comment]
Similar findings here

**Comment by CW-Jesse** [comment]
@jpw1991 The connecting issue is fixed by your #17?

**Comment by jpw1991** [comment]
It seems like it is fixed now but I don't know why. My changes shouldn't have fixed it.

**Comment by CW-Jesse** [comment]
The gods have spoken.
