### ISSUE TITLE
Compression not active in lasted game version

### ISSUE THREAD

**Issue by hisoscream** [CW-Jesse/valheim-betternetworking#21]
![image](https://github.com/CW-Jesse/valheim-betternetworking/assets/15785960/6cf056fd-85b2-4339-840d-276980f197ca)

my data send 100-120kb/s

form 40-50 with old game version

**Comment by CW-Jesse** [comment]
It looks like you've enabled verbose logging, which will tell you the size of the data before and after compression.

You may have also increased other settings that would increase your data rates, but you should see things loading in faster because of it.
