### ISSUE TITLE
server error with better networking 

### ISSUE THREAD

**Issue by KossPops** [CW-Jesse/valheim-betternetworking#22]
k_EResultLimitExceeded, k_EResultInvalidParam

we get this error when trying to load in with more than 10 people with better networking
modded 

```
## Settings file was created by plugin Better Networking v2.3.2
## Plugin GUID: CW_Jesse.BetterNetworking

[Dedicated Server]

## Requires restart.
## playfab (crossplay enabled): Forces dedicated servers to use new PlayFab networking stack.
## steamworks (crossplay disabled): Forces dedicated servers to use Steamworks network stack.
## vanilla: Listen for -crossplay flag.
# Setting type: Options_ForceCrossplay
# Default value: vanilla
# Acceptable values: vanilla, playfab, steamworks
Force Crossplay = vanilla

## Requires restart. Changes player limit for dedicated servers.
# Setting type: Int32
# Default value: 10
# Acceptable value range: From 1 to 127
Player Limit = 50

[Logging]

## Better Network's verbosity in console/logs.
# Setting type: Options_Logger_LogLevel
# Default value: message
# Acceptable values: warning, message, info
Log Level = message

[Networking]

## Keep this enabled unless comparing difference.
## ---
## Crossplay enabled: Increases speed and strength of network compression.
## Crossplay disabled: Adds network compression.
# Setting type: Options_NetworkCompression
# Default value: true
# Acceptable values: true, false
Compression Enabled = true

## Reducing this can help if your upload speed is low.
## 100%: 20 updates/second
## 75%: 15 updates/second
## 50%: 10 updates/second
# Setting type: Options_NetworkUpdateRates
# Default value: _100
# Acceptable values: _100, _75, _50
Update Rate = _100

## The better your upload speed, the higher you can set this.
## Higher options aren't available as they can cause errors in Steam.
## With compression and 100% update rate, 32 KB spikes upload speeds to 256 KB/s. (32KB*0.4*20/s)---
## If others experience lag/desync for things <i>around</i> you, increase your queue size.
## If your <i>character</i> is lagging for others, decrease your update rate and/or queue size.
# Setting type: Options_NetworkQueueSize
# Default value: _32KB
# Acceptable values: _80KB, _64KB, _48KB, _32KB, _vanilla
Queue Size = _64

[Networking (Steamworks)]

## Steamworks: The minimum speed Steam will <i>attempt</i> to send data.
## <b>Lower this below your internet upload speed.</b>
## 
# Setting type: Options_NetworkSendRateMin
# Default value: _256KB
# Acceptable values: _1024KB, _768KB, _512KB, _256KB, _150KB
Minimum Send Rate = _256KB

## Steamworks: The maximum speed Steam will <i>attempt</i> to send data.
## If you have a low upload speed, lower this <i>below</i> your internet upload speed.
## 
# Setting type: Options_NetworkSendRateMax
# Default value: _1024KB
# Acceptable values: _1024KB, _768KB, _512KB, _256KB, _150KB
Maximum Send Rate = _1024KB
```
 this is our current config settings we have
 
 
 Mod pack
Neobotics-Reely_SpecTackleLure-0.2.3
Smoothbrain-Jewelcrafting-1.5.17
Smoothbrain-CreatureLevelAndLootControl-4.5.19
Smoothbrain-Groups-1.2.6
Smoothbrain-StartupAccelerator-1.0.2
Smoothbrain-Building-1.2.5
Smoothbrain-Blacksmithing-1.2.5
Smoothbrain-Cooking-1.1.15
Smoothbrain-Ranching-1.1.3
Smoothbrain-DarwinAwards-1.0.6
Smoothbrain-Farming-2.1.12
Smoothbrain-HildirsQuest-1.0.2
Smoothbrain-Lumberjacking-1.0.5
Smoothbrain-Mining-1.1.5
Smoothbrain-Professions-1.4.1
Smoothbrain-Sailing-1.1.7
Smoothbrain-ServerCharacters-1.4.11
Smoothbrain-TombstoneLock-1.0.7
OdinPlus-OdinArchitect-1.2.7
OdinPlus-OdinHorse-1.2.6
OdinPlus-OdinsFoodBarrels-1.0.17
OdinPlus-PlantIt-0.1.5
Smoothbrain-Foraging-1.0.8
Pineapple-MoreGates-1.0.11
plumga-Clutter-0.1.6
RustyMods-Almanac-3.1.5
RustyMods-FishChum-1.0.1
SpaceDrive-BlastFurnaceAllOres-1.0.1
Tekla-AutoRepair-5.4.1602
Valphi-BetterLaddersContinued-0.217.24
Vapok-AdventureBackpacks-1.7.6
VentureValheim-Need_For_Speed-0.2.1
VentureValheim-Venture_Location_Reset-0.8.0
VentureValheim-World_Advancement_Progression-0.2.8
WackyMole-WackysDatabase-2.2.2
Therzie-Warfare-1.6.6
Therzie-Armory-1.1.8
Therzie-WarfareFireAndIce-1.1.5
Therzie-Monstrum-1.3.5
Therzie-MonstrumDeepNorth-1.1.7
Therzie-MonstrumAshlands-1.1.6
The_Bees_Decree-VALKEA-2.1.90
VentureValheim-Venture_Multiplayer_Tweaks-0.10.0
coemt-ProtectYourSeed-0.0.5
denikson-BepInExPack_Valheim-5.4.2202
ValheimModding-Jotunn-2.17.0
TastyChickenLegs-NoSmokeStayLit-2.3.1
Mayo-AAV-1.0.2
Advize-PlantEverything-1.16.2
Aicho-JowlethNoRainDamage-1.2.1
ASharpPen-Custom_Raids-1.7.10
ASharpPen-Drop_That-2.3.11
ASharpPen-Spawn_That-1.2.9
Azumatt-AzuExtendedPlayerInventory-1.3.12
Azumatt-FastLink-1.4.0
Azumatt-LimitWorkstationDiscovery-1.0.1
Azumatt-Where_You_At-1.0.9
Azumatt-AzuAntiCheat-4.3.2
Azumatt-AzuCraftyBoxes-1.2.9
Smoothbrain-Backpacks-1.3.3
Azumatt-BowsBeforeHoes-1.3.4
Azumatt-Recycle_N_Reclaim-1.3.1
Azumatt-WardIsLove-3.5.1
Azumatt-XRayVision-2.2.1
AzuRe-Spawner_Tweaks-1.24.0
BentoG-MissingPieces-2.0.7
blacks7ar-BoatAdditions-1.2.4
blacks7ar-FineWoodPieces-1.4.6
blacks7ar-NoTreeStump-1.0.1
blacks7ar-OdinsHares-1.2.2
Captain-BuildExpansion_Renewed-1.0.9
castix-FloatingItems-1.0.0
ComfyMods-ComfySigns-1.6.0
Crystal-BetterChat-1.4.9
Digitalroot-Digitalroots_Slope_Combat_Assistance-2.0.22
Digitalroot-Max_Dungeon_Rooms-2.0.30
RockerKitten-BoneAppetit-3.3.1
Frenvius-Valharvest-3.0.7
JereKuusela-Item_Stand_All_Items-1.20.0
JereKuusela-Structure_Tweaks-1.28.0
KGvalheim-Marketplace_NPC_Models-1.0.0
KGvalheim-Marketplace_And_Server_NPCs_Revamped-9.2.3
JewelHeim-Marketplace_Configs-1.0.7
KGvalheim-ItemDrawers-1.0.7
LVH-IT-UseEquipmentInWater-0.2.4
ValheimModding-HookGenPatcher-0.0.4
MaxFoxGaming-Runestone_And_Vegvisir_Prefabs-1.0.0
MSchmoecker-VNEI-0.14.1
MythikWolf-QuestItems-1.1.0
VikingHaul-VikingHaul-4.0.7
CW_Jesse-BetterNetworking_Valheim-2.3.2
RandyKnapp-MinimalStatusEffects-1.0.7
blacks7ar-HelmetBeGone-1.0.6
Frogger-ChestSnap-0.0.3
Azumatt-MouseTweaks-1.0.1
Azumatt-FirstPersonMode-1.3.1
Azumatt-AzuClock-1.0.2
Azumatt-AAA_Crafting-1.3.4
VikingHaul-VikingHaulGL-4.0.1

**Comment by CW-Jesse** [comment]
It looks like you've set `Queue Size` to `_64`, not `_64KB`.
